import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
     <head>
        <link rel="stylesheet" href="/css/vertical-layout-light/style.css" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
