import type { Metadata } from "next";
import Navbar from "../../componets/navbar";
import Sidebar from "../../componets/sidebar";

import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/vertical-layout-light/style.css" />
      </head>
      <body>
        <div className="container-scroller">
          <Navbar />
          <div className="container-fluid page-body-wrapper">
            <Sidebar />
            <div className="main-panel">{children}</div>
          </div>
        </div>

        <Script
          src="/vendors/js/vendor.bundle.base.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/vendors/typeahead.js/typeahead.bundle.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/vendors/select2/select2.min.js"
          strategy="beforeInteractive"
        />
        <Script src="/js/off-canvas.js" strategy="afterInteractive" />
        <Script src="/js/hoverable-collapse.js" strategy="afterInteractive" />
        <Script src="/js/template.js" strategy="afterInteractive" />
        <Script src="/js/settings.js" strategy="afterInteractive" />
        <Script src="/js/todolist.js" strategy="afterInteractive" />
        <Script src="/js/file-upload.js" strategy="afterInteractive" />
        <Script src="/js/typeahead.js" strategy="afterInteractive" />
        <Script src="/js/select2.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
